import 'package:flutter/material.dart';

class ChapterListScreen extends StatelessWidget {
  const ChapterListScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text('Story'),
                              ),
                                    body: Padding(
                                            padding: const EdgeInsets.all(20),
                                                    child: Column(
                                                              crossAxisAlignment: CrossAxisAlignment.start,
                                                                        children: const [
                                                                                    Text(
                                                                                                  'Beny Romance',
                                                                                                                style: TextStyle(
                                                                                                                                fontSize: 26,
                                                                                                                                                fontWeight: FontWeight.bold,
                                                                                                                                                              ),
                                                                                                                                                                          ),
                                                                                                                                                                                      SizedBox(height: 12),
                                                                                                                                                                                                  Text(
                                                                                                                                                                                                                'A romantic story unfolding chapter by chapter.\n\n'
                                                                                                                                                                                                                              'The story section is under construction.\n'
                                                                                                                                                                                                                                            'Soon, you will read, feel, and remember.',
                                                                                                                                                                                                                                                          style: TextStyle(
                                                                                                                                                                                                                                                                          fontSize: 16,
                                                                                                                                                                                                                                                                                          color: Colors.grey,
                                                                                                                                                                                                                                                                                                          height: 1.5,
                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                Spacer(),
                                                                                                                                                                                                                                                                                                                                                            Center(
                                                                                                                                                                                                                                                                                                                                                                          child: Text(
                                                                                                                                                                                                                                                                                                                                                                                          '🌙✨',
                                                                                                                                                                                                                                                                                                                                                                                                          style: TextStyle(fontSize: 32),
                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  